---
- name: Configure Application Server
  hosts: app_servers
  become: yes

  tasks:
    - name: Install required packages
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - nginx
        - python3
        - python3-pip
        

    - name: Ensure Nginx is running
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Copy application files
      copy:
        src: /path/to/your/application/files
        dest: /var/www/html/
      notify:
        - Restart Nginx

  handlers:
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
